### ISSUE TITLE
Cant install mods, called Result::unwrap() on an 'Err' value.

### ISSUE THREAD

**Issue by NafzorOB** [AOx0/rrm#9]
So i tried to install rocketman using `rrm install "https://steamcommunity.com/sharedfiles/filedetails/?id=2479389928"` but this throws an error:
```

bash-5.2$ rrm install "https://steamcommunity.com/sharedfiles/filedetails/?id=2479389928"
      Status Installing mod
thread '<unnamed>' panicked at src/install.rs:259:113:
called `Result::unwrap()` on an `Err` value: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at src/install.rs:334:30:
called `Result::unwrap()` on an `Err` value: Any { .. }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
   3: rrm::install::install::{{closure}}
   4: tokio::runtime::park::CachedParkThread::block_on
   5: tokio::runtime::context::runtime::enter_runtime
   6: tokio::runtime::runtime::Runtime::block_on
   7: rrm::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Im currently on Void Linux, and i used the current git version.

**Comment by AOx0** [comment]
Hi, I'm sorry you're experiencing problems with the software. 

Did you follow [this](https://github.com/AOx0/rrm/wiki#first-run) first step?

**Comment by NafzorOB** [comment]
Yes, it installed steamcmd succesfully and i set the game path but the problem continues

**Comment by AOx0** [comment]
Ok, the latest commit should work now

**Comment by AOx0** [comment]
At least on Arch the problem was the software looks at `~/.rrm/.steam` for the downloads but steamcmd puts them at `~/.rrm/Steam`, I guess it's beacause of an update since I remember it used to work fine.

**Comment by NafzorOB** [comment]
After compiling the git version and trying to run rrm install i get this error

```
~/rrm/target/debug> ./rrm install "3092175321"                                                                                                                               

thread 'main' panicked at /home/nafzor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap-3.2.5/src/builder/debug_asserts.rs:237:13:
Command install: Argument or group 'authors' specified in 'conflicts_with*' for 'all' does not exist
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: clap::builder::debug_asserts::assert_app
             at /home/nafzor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap-3.2.5/src/builder/debug_asserts.rs:237:13
   3: clap::builder::command::App::_build_self
             at /home/nafzor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap-3.2.5/src/builder/command.rs:4256:13
   4: clap::builder::command::App::_build_subcommand
             at /home/nafzor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap-3.2.5/src/builder/command.rs:4340:9

   5: clap::parser::parser::Parser::parse_subcommand
             at /home/nafzor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap-3.2.5/src/parser/parser.rs:676:27
   6: clap::parser::parser::Parser::get_matches_with
             at /home/nafzor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap-3.2.5/src/parser/parser.rs:469:13
   7: clap::builder::command::App::_do_parse
             at /home/nafzor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap-3.2.5/src/builder/command.rs:4120:29
   8: clap::builder::command::App::try_get_matches_from_mut
             at /home/nafzor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap-3.2.5/src/builder/command.rs:686:9
   9: clap::builder::command::App::get_matches_from
             at /home/nafzor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap-3.2.5/src/builder/command.rs:556:9
  10: clap::builder::command::App::get_matches
             at /home/nafzor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap-3.2.5/src/builder/command.rs:468:9
  11: clap::derive::Parser::parse
             at /home/nafzor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap-3.2.5/src/derive.rs:83:27
  12: rrm::args::App::load
             at /home/nafzor/rrm/src/args.rs:372:9
  13: rrm::main::{{closure}}
             at /home/nafzor/rrm/src/main.rs:17:27
  14: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/nafzor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.19.2/src/park/thread.rs:263:54
  15: tokio::coop::with_budget::{{closure}}
             at /home/nafzor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.19.2/src/coop.rs:102:9
  16: std::thread::local::LocalKey<T>::try_with
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/thread/local.rs:270:16
  17: std::thread::local::LocalKey<T>::with
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/thread/local.rs:246:9
  18: tokio::coop::with_budget
             at /home/nafzor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.19.2/src/coop.rs:95:5
  19: tokio::coop::budget
             at /home/nafzor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.19.2/src/coop.rs:72:5
  20: tokio::park::thread::CachedParkThread::block_on
             at /home/nafzor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.19.2/src/park/thread.rs:263:31
  21: tokio::runtime::enter::Enter::block_on
             at /home/nafzor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.19.2/src/runtime/enter.rs:151:13
  22: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/nafzor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.19.2/src/runtime/thread_pool/mod.rs:90:9
  23: tokio::runtime::Runtime::block_on
             at /home/nafzor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.19.2/src/runtime/mod.rs:482:43
  24: rrm::main
             at /home/nafzor/rrm/src/main.rs:29:5
  25: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by AOx0** [comment]
Hm, I can replicate the issue with a debug build but a release build or a normal `cargo install --path .` works with `rrm install "3092175321"`

**Comment by NafzorOB** [comment]
Seems to work correctly after using a release version.
